#!/usr/bin/env bash

kind="$1"
case "$kind" in
rollup)
  yarn rollup -c --bundleConfigAsCjs
  ;;
declaration)
  tsc --project tsconfig.declaration.json --outDir dist/typings --declaration --emitDeclarationOnly
  ;;
*)
  echo >&2 "Unknown build kind '$kind'. Expected rollup or declaration."
  exit 1
  ;;
esac
